### ISSUE TITLE
how to create issue then parse the json to send to discord?

### ISSUE THREAD

**Issue by BunkDev5674** [samkgpt/github-apis#1]

**Comment by samkgpt** [comment]
** Create an issue on a repository**

const options = {
        token: "1e3ed294c3f7tce7btdcdg18t88d98b743f9ac48t135656",
        owner: "owner", // owner or user
        repo: "repo",
        body: {
        title: "title", // required
        body: "body",
        state: "open", // open or closed
        labels: ["bug", "dev"],
  },
};

(async () => {
  await createIssue(options).then(response => {                   
                    return response;
                })
                .catch(err => {
                    return err;
       });
})();
